# This is a basic workflow to help you get started with Actions
name: main-workflow
run-name: ${{ github.actor }} is pushing into the main branch üöÄ

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# env:
#   GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

# permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Testing github actions job
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."

  # Defining different jobs: quality / build / deploy ...

  # Quality job
  # dependencies:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.20.0
  #         cache: 'npm'

  #     - name: Cache Node Modules
  #       id: node-cache
  #       uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  #     - name: Install Dependencies
  #       run: npm ci --cache .npm --prefer-offline

  # # Quality job
  # quality:
  #   needs: dependencies
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
  # steps:
  #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #   - uses: actions/checkout@v3
  #   - name: Setup Node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 18.20.0
  #       cache: 'npm'
  #   - uses: actions/cache@v3
  #     with:
  #       path: node_modules
  #       key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  #   # Nx lint
  #   - name: Running linter on all projects
  #     run: npx nx run-many --target=lint --all
  #   # Nx format
  #   - name: Checking format on all projects
  #     run: npx nx format:check --all
  #   # Nx test
  #   - name: Running jest test-runner on all projects
  #     run: npx nx run-many --target=test --all

  # E2E job
  # e2e:
  #   needs: dependencies
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: node-modules-${{ hashFiles('package-lock.json') }}

  #     # Nx e2e
  #     - name: Running cypress on Front
  #       run: npx nx run my-hobby-place-front-e2e:e2e

  # Build job
  build:
    # needs: quality
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Cache dependencies and build outputs
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # Nx build
      - name: Running build
        run: npx nx run-many --target=build --all

      # Uploading build dist artifact
      - name: Archiving build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_dist_artifact
          path: dist
          retention-days: 5

  # Semantic-Release job
  # semantic-release:
  #   needs: build
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.20.0
  #         cache: 'npm'
  #     - uses: actions/cache@v3
  #       with:
  #         path: node_modules
  #         key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  # Trigger semantic release
  # - name: Running Semantic-Release
  #   run: npx semantic-release@22.0.12
